CREATE TABLE IF NOT EXISTS RENDELESFEJ 
	(rend_szam VARCHAR(9) PRIMARY KEY ,partner_kod VARCHAR(5),rend_datum DATE);

CREATE TABLE IF NOT EXISTS TERMEK 
	(kod VARCHAR(5) PRIMARY KEY, nev VARCHAR(30), ar INT);

CREATE TABLE IF NOT EXISTS RENDELES 
		(rend_szam VARCHAR(9), FOREIGN KEY(rend_szam) REFERENCES RENDELESFEJ, kod VARCHAR(5),
	 	FOREIGN KEY(kod) REFERENCES TERMEK, darab INT, datum DATE, kesz TINYINT);

CREATE TABLE IF NOT EXISTS ANYAG 
	(azonosito INT PRIMARY KEY ,neve VARCHAR(20), mert_egys VARCHAR(5), egys_ar DOUBLE, keszlet INT);

CREATE TABLE IF NOT EXISTS SZERKEZET
	(kod VARCHAR(5), FOREIGN KEY(kod) REFERENCES TERMEK, azonosito INT, FOREIGN KEY(azonosito) REFERENCES ANYAG, mennyiseg INT);

CREATE TABLE IF NOT EXISTS REND_HONAP 
	(rend_szam VARCHAR(10) ,UNIQUE KEY UK_rend_szam(rend_szam) , ertek INT, honap VARCHAR(30));

CREATE TABLE IF NOT EXISTS PARTNER 	
	(partner_kod INT);

CREATE TABLE IF NOT EXISTS TERMEKARAK 	
	(kod VARCHAR(10),UNIQUE KEY UK_kod(kod), aar INT);

CREATE TABLE IF NOT EXISTS MINOSIT
	(szoveg VARCHAR(10), also INT);
