CREATE TABLE IF NOT EXISTS RENDELESFEJ (rend_szam VARCHAR(9) PRIMARY KEY ,partner_kod VARCHAR(5),rend_datum DATE);
CREATE TABLE IF NOT EXISTS TERMEK (kod VARCHAR(5) PRIMARY KEY, nev VARCHAR(30), ar INT);
CREATE TABLE IF NOT EXISTS RENDELES (rend_szam VARCHAR(9), FOREIGN KEY(rend_szam) REFERENCES RENDELESFEJ, kod VARCHAR(5), FOREIGN KEY(kod) REFERENCES TERMEK, darab INT, datum DATE, kesz TINYINT);
CREATE TABLE IF NOT EXISTS ANYAG (azonosito INT PRIMARY KEY , neve VARCHAR(20), mert_egys VARCHAR(5), egys_ar DOUBLE, keszlet INT);
CREATE TABLE IF NOT EXISTS SZERKEZET (kod VARCHAR(5), FOREIGN KEY(kod) REFERENCES TERMEK, azonosito INT, FOREIGN KEY(azonosito) REFERENCES ANYAG, mennyiseg INT);